# Use YAML for configuration since it allows comments like this
site_name: Agrogeophysic 2nd seminar
description: Agrogeophysic 2nd seminar website
author: Benjamin Mary
language: en
repository: agrogeophy/2nd_agrogeophysics_seminar
favicon: images/Garre_drawing1.png
logo: images/Garre_drawing2.png
menu:
  - [Home, index]  
  - [Committees, committees]
  - [Program, program]
ignore:
  - README.md
  - config-alternative.json
  - Makefile
keywords: 'agrogeophysic, applied geophysics, remote sensing, open-source'
language: en

